spring.application.name=SpringBootExceptionHandling
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/Security
spring.datasource.username=postgres
spring.datasource.password=Branchburg@26