spring.application.name=HotelService
server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5432/Microservice-Project
spring.datasource.username=postgres
spring.datasource.password=Branchburg@26
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true