spring.application.name=OauthSecurity
server.port=8082
spring.security.oauth2.client.registration.google.client-id=XXXXX
spring.security.oauth2.client.registration.google.client-secret=XXXXX

spring.security.oauth2.client.registration.github.client-id=XXXXXYYYYY
spring.security.oauth2.client.registration.github.client-secret=XXXXYYYYY
#Create the Ouath id and secret

#get the client-id and client-secret from google clould console

#open google cloud console-console-create or select new project-API&services-credential->create new credentials
#->OuthClientId->configure Consent Screen->External->app name-developer emails
#Add test Users ->create Oauth client Id->Web application->redirected URL->http://localhost:8082/login/oauth2/code/google
#then get client id and secret