spring.application.name=Spring-Batch-Project
spring.datasource.url=jdbc:postgresql://localhost:5432/Spring-Batch
spring.datasource.username=postgres
spring.datasource.password=Branchburg@26
#schema.sql and data.sql will not run everytime application runs if i set it for never
spring.sql.init.mode=never
#jpa will not create or update table with java class name .it just connects db but it will not make any changes in the db table
#for none
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#as soon as application starts spring batch job will run
spring.batch.job.enabled=true

app.batch.chunk-size=2
app.batch.grid-size=4
app.batch.page-size=2
app.batch.thread-pool.core-size=2
app.batch.thread-pool.max-size=4
app.batch.thread-pool.queue-capacity=20
