spring.application.name=UserService
spring.datasource.url=jdbc:postgresql://localhost:5432/Microservice-Project
spring.datasource.username=postgres
spring.datasource.password=Branchburg@26
server.port=8086
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update